### PR TITLE
[Discussion Only - No Need to Merge] potential fund transfer issue in "ExecuteOrders"

### PR DESCRIPTION
**Pull request by nonstopcoderaxw**
Hey Bokky, I've been running some additional test cases and found the following. It could be a security vulnerability but I couldn't wrong so would like to discuss with you. This pull request includes the test case that allows a maker to sell a NFT not owned by the maker by still receive funds. Details are below.

- Maker adds a sell order for a slightly modified ERC721 shown the pull request. The tokenId in the order is not owned by this maker. This modified ERC721 looks still legit and will return the same interfaceid as a openzeppelin standard ERC721.
- Taker executes this order not knowing this NFT is not owned by the maker.  The safeTransferFrom in ExecuteOrders will return false and the "ExecuteOrders" call will continue.  Tx will go through successfully. Taker will eventually pay the fund to the Maker. 

The test case can be replicated by commands below. Comments in "00_test_0.js" explains the test case details. I will leave this repo unchanged for you. 

```
git clone -b for_bokky https://github.com/nonstopcoderaxw/Nix
cd Nix
npm install
npx hardhat test > testIt.out
```

If my understand above is all correct, I would suggest to do an "ERC721.ownerOf" check before the "transferNetted" call. Otherwise, someone could deploy an NFT into another marketplace and make a sale and then list the same tokenId in Nix to double sell. 

Please let me know how your thoughts. Free feel to correct me on any mistakes I made. 

Cheers.

### CODE REVIEW

**Comment by bokkypoobah** [comment]
I don't think this is an issue with the Nix smart contract, as this exchange assumes that the traded ERC-721 adheres to https://eips.ethereum.org/EIPS/eip-721 .

image

**Comment by nonstopcoderaxw** [comment]
Just to help me better understand "this exchange assumes that the traded ERC-721 adheres", how does the contract itself ensures the listed ERC721 strictly implements the EIP standard and will definitely throw an exception if the maker is not the owner of the tokenid?

FYI. I've also tested with the Nix App UI in Rinkeby. Below shows the same tokenId got executed twice. You can execute this order again if you like. The expected result is No NFT received but weth paid. 

Screen Shot 2021-12-13 at 6 27 35 pm

The screenshot below is an "executeOrders" call in Rinkeby done via Nix App. It doesn't include ERC721 transfer but two ERC20 transfer for WETH.
Screen Shot 2021-12-13 at 6 43 52 pm

https://rinkeby.etherscan.io/tx/0x8337bee9ea6390a0d8276d1fadfb24690ed6db84f0245f177eae5ea89a93280a

**Comment by bokkypoobah** [comment]
I'll document the explanation and ping back.

**Comment by nonstopcoderaxw** [comment]
> I'll document the explanation and ping back.

Awesome. Thanks Bokky!

**Comment by bokkypoobah** [comment]
Not an issue

**Pull request closed without merging**
